name: Build & upload to Firebase App Distribution 
on:
  push: 
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  Test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload apk to Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with: 
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build\app\outputs\flutter-apk\app-release.apk
 
        

