name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: $
          channel: 'stable'
      - run: flutter pub get
