name: build file apk
on:
  push:
    branches: [master]
  pull-request: 
    branches: [master]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checout@v2
