name: CI
on:
  push: 
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  Test-app:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
  Build-app:
    needs: Test-app
    runs-on: windows-latest
    steps:
      Build-file-apk:
        - run: flutter build apk --release
        - name: Create a Release APK
        - uses: actions/upload-artifact@v2
          with:
            path: build/app/outputs/flutter-apk/app-release.apk


