name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: windows-latest
    env:
      JAVA_VERSION: "1.8"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - uses: actions/checkout@v2
        with:
          flutter-version: $
      - uses: actions/sobusito/flutter-action@v2
      - run: flutter pub get
