name: Analyze pull request

on:
  push:
    branches:
      - 'master'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository on branch:"
        uses: actions/checkout@v2
      - name: Install Fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm
      - name: Setup Flutter
        run: fvm install
      - name: Get all flutter deplendencies
        run: fvm flutter pub get
      - name: Run tests with User feedback (in case some test are failing)
        run: fvm flutter test
